basescan_api_key="JWEDJD132KK3R74NXGKYZC8YQJ7MZZ4IJF"
friendtech_wallet="0xdd9176eA3E7559D6B68b537eF555D3e89403f742"
friendtech_contract="0xcf205808ed36593aa40a44f10c7f7c2f67d4a4d4"
auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoiMHg2NThjZjg5ZjcxMThhZDFmNzRjMWZlNTc1MDJlNzYwNTM3MDhiMTQ1IiwiaWF0IjoxNjkyOTczOTkxLCJleHAiOjE2OTU1NjU5OTF9.miDBxDLQwidxKZzECEUGyxxI2sDMQSzX98vueKb-PJs"